const cardsData = [
    {
        "NOME":  "Cadeirinha Invisível",
        "MISSÃO":  "Sentar na cadeirinha invisível para descansar na floresta, sem deixar ela quebrar!",
        "MATERIAL NECESSÁRIO":  "Nenhum",
        "CRIANÇA FAZ":  "Imita a mãe, tentando sentar na sua própria cadeirinha imaginária.",
        "MÃE FAZ":  "Agachamento clássico, com pés na largura dos ombros.",
        "INTERAÇÃO":  "Contam juntos \"1, 2, 3\" antes de levantar da cadeirinha.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Agachamento parcial (movimento mais curto).",
        "NÍVEL 2 (AVANÇADO)":  "Agachamento completo (quadril abaixo da linha dos joelhos).",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Passo do Caranguejo",
        "MISSÃO":  "Andar de lado como um caranguejo para fugir da onda do mar!",
        "MATERIAL NECESSÁRIO":  "Nenhum",
        "CRIANÇA FAZ":  "Imita um caranguejo, andando de lado com as pernas abertas.",
        "MÃE FAZ":  "Agachamento sumô (pernas bem afastadas, pontas dos pés para fora).",
        "INTERAÇÃO":  "Fazem o som do caranguejo (\"ploc, ploc\") juntos enquanto se movem.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Fazer o agachamento com amplitude menor.",
        "NÍVEL 2 (AVANÇADO)":  "Agachar até a amplitude máxima, segurando 1 segundo embaixo.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Passo Silencioso",
        "MISSÃO":  "Dar um passo para trás bem devagar para não assustar o passarinho.",
        "MATERIAL NECESSÁRIO":  "Nenhum",
        "CRIANÇA FAZ":  "Tenta imitar o passo para trás da mãe, focando no equilíbrio.",
        "MÃE FAZ":  "Afundo Reverso (passo para trás, flexionando os joelhos).",
        "INTERAÇÃO":  "Ambos fazem o sinal de \"shhh\" com o dedo na boca a cada passo.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Passo curto, com pouca descida do joelho.",
        "NÍVEL 2 (AVANÇADO)":  "Passo longo, quase tocando o joelho de trás no chão.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Reverência do Rei",
        "MISSÃO":  "Fazer a reverência (cumprimento) para o rei e a rainha do castelo.",
        "MATERIAL NECESSÁRIO":  "Nenhum",
        "CRIANÇA FAZ":  "Inclina o tronco para frente, imitando um cumprimento real.",
        "MÃE FAZ":  "Exercício \"Bom Dia\" (inclinação de tronco com costas retas).",
        "INTERAÇÃO":  "Um é o rei/rainha e o outro faz a reverência, depois trocam os papéis.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Inclinação curta, com a mão na lombar para garantir a postura.",
        "NÍVEL 2 (AVANÇADO)":  "Inclinação até o tronco ficar quase paralelo ao chão.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Ponte Levadiça",
        "MISSÃO":  "Levantar a ponte bem alto para os barquinhos passarem por baixo!",
        "MATERIAL NECESSÁRIO":  "Tapete",
        "CRIANÇA FAZ":  "Passa por baixo do quadril da mãe com um carrinho ou engatinhando.",
        "MÃE FAZ":  "Elevação pélvica, deitada de barriga para cima.",
        "INTERAÇÃO":  "A criança avisa \"Barquinho vindo!\" e a mãe tem que subir a ponte.",
        "TEMPO":  "2-3 min",
        "NÍVEL 1 (INICIANTE)":  "Subir e descer devagar.",
        "NÍVEL 2 (AVANÇADO)":  "Segurar 3 segundos no topo, contraindo forte o glúteo.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Escada Mágica",
        "MISSÃO":  "Subir a escada mágica, degrau por degrau, para alcançar o topo da torre.",
        "MATERIAL NECESSÁRIO":  "Cadeira firme ou degrau para a mãe; almofada para a criança.",
        "CRIANÇA FAZ":  "Sobe e desce da almofada ou de um degrau baixo.",
        "MÃE FAZ":  "Step-Up na cadeira, alternando as pernas.",
        "INTERAÇÃO":  "Contam os \"degraus\" juntos a cada subida.",
        "TEMPO":  "2-3 min",
        "NÍVEL 1 (INICIANTE)":  "Usar um apoio mais baixo (um livro grosso).",
        "NÍVEL 2 (AVANÇADO)":  "Fazer o movimento sem apoiar as mãos em nada.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Pega-Pega Lateral",
        "MISSÃO":  "Desviar de um lado para o outro para não ser pego na brincadeira!",
        "MATERIAL NECESSÁRIO":  "Nenhum",
        "CRIANÇA FAZ":  "Corre de um lado para o outro.",
        "MÃE FAZ":  "Afundo Lateral, alternando os lados.",
        "INTERAÇÃO":  "A mãe tenta \"pegar\" a criança ao se mover para o lado dela.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Dar um passo lateral e agachar pouco.",
        "NÍVEL 2 (AVANÇADO)":  "Agachar o máximo possível na lateral.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Ponta do Pé Curiosa",
        "MISSÃO":  "Ficar na ponta do pé para conseguir espiar por cima do muro!",
        "MATERIAL NECESSÁRIO":  "Nenhum",
        "CRIANÇA FAZ":  "Fica na ponta dos pés, tentando ver algo longe.",
        "MÃE FAZ":  "Elevação de Panturrilha, em pé.",
        "INTERAÇÃO":  "A cada subida, um dos dois diz o que \"viu\" do outro lado do muro.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Fazer o movimento livre.",
        "NÍVEL 2 (AVANÇADO)":  "Segurar 2 segundos na posição mais alta.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Muro do Castelo",
        "MISSÃO":  "Segurar o muro do castelo com as costas para ele não cair!",
        "MATERIAL NECESSÁRIO":  "Parede livre",
        "CRIANÇA FAZ":  "Tenta \"empurrar\" os joelhos da mãe (de leve) para testar a força do muro.",
        "MÃE FAZ":  "Agachamento Isométrico na parede.",
        "INTERAÇÃO":  "A criança é o \"dragão\" que testa a força do muro.",
        "TEMPO":  "30-45s",
        "NÍVEL 1 (INICIANTE)":  "Posição mais alta (joelhos menos flexionados).",
        "NÍVEL 2 (AVANÇADO)":  "Posição a 90 graus (como se estivesse sentada).",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Cachorrinho no Poste",
        "MISSÃO":  "Imitar o cachorrinho feliz que levanta a patinha no poste!",
        "MATERIAL NECESSÁRIO":  "Tapete",
        "CRIANÇA FAZ":  "Em quatro apoios, imita o cachorrinho.",
        "MÃE FAZ":  "Exercício \"Hidrante\" (elevação lateral de perna).",
        "INTERAÇÃO":  "Fazem o som do cachorrinho (\"au au!\") e trocam de \"patinha\" (perna) juntos.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Movimento com amplitude curta.",
        "NÍVEL 2 (AVANÇADO)":  "Segurar 2 segundos na posição mais alta.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Coice de Cavalinho",
        "MISSÃO":  "Ser um cavalinho forte e dar um coice para o céu!",
        "MATERIAL NECESSÁRIO":  "Tapete",
        "CRIANÇA FAZ":  "Em quatro apoios, imita o coice.",
        "MÃE FAZ":  "Elevação de perna em quatro apoios (coice de glúteo).",
        "INTERAÇÃO":  "Relincham como cavalinhos a cada coice.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Movimento lento e controlado.",
        "NÍVEL 2 (AVANÇADO)":  "Pulsar 3 vezes no topo antes de descer a perna.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Ponte de Uma Perna Só",
        "MISSÃO":  "Levantar a ponte usando a super-força de uma perna só!",
        "MATERIAL NECESSÁRIO":  "Tapete",
        "CRIANÇA FAZ":  "Tenta se equilibrar em um pé só, imitando a mãe.",
        "MÃE FAZ":  "Elevação pélvica unilateral.",
        "INTERAÇÃO":  "A criança ajuda a contar quantas vezes a \"ponte forte\" sobe.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Manter a perna elevada flexionada, em vez de esticada.",
        "NÍVEL 2 (AVANÇADO)":  "Manter o quadril perfeitamente alinhado.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Pedalando na Floresta",
        "MISSÃO":  "Pedalar nossa bicicleta imaginária bem rápido para fugir do lobo!",
        "MATERIAL NECESSÁRIO":  "Tapete",
        "CRIANÇA FAZ":  "Deitada, imita o movimento de pedalar no ar.",
        "MÃE FAZ":  "Abdominal bicicleta clássico.",
        "INTERAÇÃO":  "A mãe narra a perseguição: \"Mais rápido, o lobo está chegando!\".",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Fazer o movimento com os pés mais altos e ritmo lento.",
        "NÍVEL 2 (AVANÇADO)":  "Fazer o movimento com as pernas mais próximas ao chão.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Barquinho no Rio",
        "MISSÃO":  "Remar nosso barquinho para chegar na cachoeira secreta!",
        "MATERIAL NECESSÁRIO":  "Tapete",
        "CRIANÇA FAZ":  "Pula por cima das pernas da mãe cada vez que elas se esticam.",
        "MÃE FAZ":  "Abdominal remador.",
        "INTERAÇÃO":  "A mãe avisa \"Cuidado com a onda!\" quando a criança precisa pular.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Fazer o movimento com os joelhos sempre um pouco flexionados.",
        "NÍVEL 2 (AVANÇADO)":  "Esticar completamente braços e pernas.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Escalando a Montanha",
        "MISSÃO":  "Escalar a montanha de gelo para chegar ao topo!",
        "MATERIAL NECESSÁRIO":  "Cadeira firme ou sofá.",
        "CRIANÇA FAZ":  "Imita o movimento de escalada em pé ou no chão.",
        "MÃE FAZ":  "Escalador (mountain climber) com mãos apoiadas na cadeira.",
        "INTERAÇÃO":  "Contam juntos cada \"passo\" na escalada.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Movimento lento e controlado.",
        "NÍVEL 2 (AVANÇADO)":  "Aumentar a velocidade, como se estivesse correndo.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Robô Giratório",
        "MISSÃO":  "Virar um robô que olha para todos os lados para vigiar o laboratório!",
        "MATERIAL NECESSÁRIO":  "Nenhum",
        "CRIANÇA FAZ":  "Imita o robô, girando o tronco de um lado para o outro.",
        "MÃE FAZ":  "Rotação de tronco em pé com elevação de joelho.",
        "INTERAÇÃO":  "Fazem sons de robô (\"bip, bop\") a cada rotação.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Fazer o movimento sem elevar muito o joelho.",
        "NÍVEL 2 (AVANÇADO)":  "Tocar o cotovelo no joelho oposto.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Caranguejo Pega-Estrela",
        "MISSÃO":  "Ser um caranguejo que estica a patinha para pegar as estrelas do fundo do mar!",
        "MATERIAL NECESSÁRIO":  "Tapete",
        "CRIANÇA FAZ":  "Anda pela sala como um caranguejo (ponte invertida).",
        "MÃE FAZ":  "Em posição de ponte invertida, toca a mão no pé oposto.",
        "INTERAÇÃO":  "Competem para ver quem \"pega mais estrelas\".",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Apenas levantar a mão, sem tentar tocar no pé.",
        "NÍVEL 2 (AVANÇADO)":  "Tocar a ponta do pé a cada repetição.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Super-Herói Voador",
        "MISSÃO":  "Voar como um super-herói, esticando braço e perna para ganhar velocidade!",
        "MATERIAL NECESSÁRIO":  "Tapete",
        "CRIANÇA FAZ":  "Imita um super-herói voando.",
        "MÃE FAZ":  "Perdigueiro (em 4 apoios, estende braço e perna opostos).",
        "INTERAÇÃO":  "A mãe narra a aventura do voo sobre a cidade.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Levantar apenas um membro de cada vez.",
        "NÍVEL 2 (AVANÇADO)":  "Segurar a posição por 3 segundos de cada lado.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Limpador de Para-brisa",
        "MISSÃO":  "Limpar o vidro do carro para podermos ver a chuva indo embora!",
        "MATERIAL NECESSÁRIO":  "Tapete",
        "CRIANÇA FAZ":  "Imita o movimento do limpador com os braços.",
        "MÃE FAZ":  "Deitada, deixa os joelhos flexionados caírem para cada lado.",
        "INTERAÇÃO":  "A criança comanda a velocidade do \"limpador\".",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Manter os pés apoiados no chão durante o movimento.",
        "NÍVEL 2 (AVANÇADO)":  "Fazer com os pés elevados.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Estrela do Mar",
        "MISSÃO":  "Ficar firme como uma estrela do mar no fundo do oceano!",
        "MATERIAL NECESSÁRIO":  "Tapete",
        "CRIANÇA FAZ":  "Deita no chão e se estica, imitando uma estrela do mar.",
        "MÃE FAZ":  "Prancha Lateral, apoiada no cotovelo.",
        "INTERAÇÃO":  "A criança pode fazer cócegas na \"estrela do mar\" (mãe).",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Prancha lateral com os joelhos apoiados no chão.",
        "NÍVEL 2 (AVANÇADO)":  "Prancha lateral completa.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Túnel Infinito",
        "MISSÃO":  "Manter o túnel firme para o trem passar sem bater!",
        "MATERIAL NECESSÁRIO":  "Tapete",
        "CRIANÇA FAZ":  "Engatinha por baixo do corpo da mãe.",
        "MÃE FAZ":  "Posição de Prancha Alta (mãos no chão).",
        "INTERAÇÃO":  "A mãe faz o som do apito do trem (\"piuííí!\") para a criança passar.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Prancha Alta com os joelhos apoiados no chão.",
        "NÍVEL 2 (AVANÇADO)":  "Prancha Alta completa.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Caverna do Urso",
        "MISSÃO":  "Andar como um urso forte e pesado dentro da sua caverna.",
        "MATERIAL NECESSÁRIO":  "Nenhum",
        "CRIANÇA FAZ":  "Anda em quatro apoios (mãos e pés no chão), imitando um urso.",
        "MÃE FAZ":  "Posição de \"Urso\" Isométrica (joelhos flutuando).",
        "INTERAÇÃO":  "Ambos andam pela \"caverna\", fazendo sons de urso.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Manter a posição parada (isometria).",
        "NÍVEL 2 (AVANÇADO)":  "Dar pequenos passos para frente e para trás na posição.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Empurra o Castelo",
        "MISSÃO":  "Usar nossa super-força para empurrar o portão pesado do castelo!",
        "MATERIAL NECESSÁRIO":  "Parede ou sofá firme",
        "CRIANÇA FAZ":  "\"Ajuda\" a empurrar a parede ao lado da mãe.",
        "MÃE FAZ":  "Flexão inclinada na parede ou sofá.",
        "INTERAÇÃO":  "A criança dá o comando \"Agora!\" e ambas empurram juntas.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Fazer na parede, com o corpo mais em pé.",
        "NÍVEL 2 (AVANÇADO)":  "Fazer no sofá, com o corpo mais inclinado.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Cabo de Guerra do Abraço",
        "MISSÃO":  "Puxar a corda mágica para trazer seu amigo para um super abraço!",
        "MATERIAL NECESSÁRIO":  "Toalha de rosto",
        "CRIANÇA FAZ":  "Segura uma ponta da toalha com as duas mãos.",
        "MÃE FAZ":  "Remada Sentada com toalha.",
        "INTERAÇÃO":  "É um \"cabo de guerra do bem\". A cada puxada, a mãe diz \"Vem!\".",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Manter o tronco mais reto, com menos inclinação.",
        "NÍVEL 2 (AVANÇADO)":  "Inclinar mais o tronco para trás (costas retas).",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Mergulho do Pinguim",
        "MISSÃO":  "Ser um pinguim que mergulha na água gelada para pegar peixinhos!",
        "MATERIAL NECESSÁRIO":  "Cadeira firme ou sofá",
        "CRIANÇA FAZ":  "Imita um pinguim andando e batendo as \"asas\".",
        "MÃE FAZ":  "Mergulho de tríceps no banco/cadeira.",
        "INTERAÇÃO":  "A cada \"mergulho\", a criança pega um \"peixinho\" imaginário.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Flexionar pouco os cotovelos (movimento curto).",
        "NÍVEL 2 (AVANÇADO)":  "Descer até os cotovelos formarem um ângulo de 90 graus.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "O Músculo do Super-Herói",
        "MISSÃO":  "Mostrar nosso super músculo para assustar o vilão!",
        "MATERIAL NECESSÁRIO":  "Opcional: garrafinhas de água",
        "CRIANÇA FAZ":  "Imita a mãe, flexionando o cotovelo e mostrando o \"muque\".",
        "MÃE FAZ":  "Rosca Bíceps, de pé ou sentada.",
        "INTERAÇÃO":  "Fazem caretas de \"fortões\". A cada 5 repetições, gritam \"Super Força!\".",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Fazer sem peso, com contração muscular.",
        "NÍVEL 2 (AVANÇADO)":  "Usar garrafinhas com água como peso.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "O Voo da Águia",
        "MISSÃO":  "Bater nossas asas como uma águia gigante voando sobre as montanhas!",
        "MATERIAL NECESSÁRIO":  "Opcional: garrafinhas de água",
        "CRIANÇA FAZ":  "Imita o voo da águia, abrindo e fechando os braços.",
        "MÃE FAZ":  "Elevação Lateral para ombros.",
        "INTERAÇÃO":  "Ambos \"voam\" juntos, fazendo o som da águia.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Fazer o movimento sem peso, cotovelos levemente flexionados.",
        "NÍVEL 2 (AVANÇADO)":  "Usar um peso leve (garrafinhas).",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Puxando o Tesouro",
        "MISSÃO":  "Puxar o baú do tesouro que está preso no fundo do navio pirata!",
        "MATERIAL NECESSÁRIO":  "Cabo de vassoura",
        "CRIANÇA FAZ":  "Senta na frente da mãe e segura no meio do cabo, sendo \"puxada\".",
        "MÃE FAZ":  "Remada Curvada com cabo de vassoura.",
        "INTERAÇÃO":  "A cada puxada, a mãe diz \"Está quase vindo!\".",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Fazer o movimento com pouca inclinação do tronco.",
        "NÍVEL 2 (AVANÇADO)":  "Inclinar o tronco a 45 graus, com costas retas.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Empurrando o Teto",
        "MISSÃO":  "Usar nossa força para empurrar o teto da caverna que está caindo!",
        "MATERIAL NECESSÁRIO":  "Opcional: almofadas pequenas",
        "CRIANÇA FAZ":  "Senta e empurra o ar (ou as almofadas) para cima.",
        "MÃE FAZ":  "Desenvolvimento de ombros sentado no chão.",
        "INTERAÇÃO":  "Contam juntos \"1, 2, 3... Empurra!\".",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Fazer o movimento sem peso.",
        "NÍVEL 2 (AVANÇADO)":  "Usar almofadas ou garrafinhas como peso.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Dança Congelada",
        "MISSÃO":  "Dançar com passos malucos e congelar como uma estátua quando a música parar!",
        "MATERIAL NECESSÁRIO":  "Opcional: música",
        "CRIANÇA FAZ":  "Dança junto com a mãe, imitando os passos dela.",
        "MÃE FAZ":  "Lidera a dança com passos aeróbicos simples.",
        "INTERAÇÃO":  "Quando a música para, ambos congelam. O primeiro a se mexer perde.",
        "TEMPO":  "2-3 min",
        "NÍVEL 1 (INICIANTE)":  "Movimentos mais lentos.",
        "NÍVEL 2 (AVANÇADO)":  "Aumentar a velocidade dos passos de dança.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Pula-Feijão",
        "MISSÃO":  "Pular por cima dos \"saquinhos de feijão mágicos\" sem encostar neles!",
        "MATERIAL NECESSÁRIO":  "Livros ou fitas no chão",
        "CRIANÇA FAZ":  "Pula com os dois pés de um lado para o outro dos objetos.",
        "MÃE FAZ":  "Salto lateral com os dois pés (ou passo lateral rápido).",
        "INTERAÇÃO":  "Ambos pulam juntos sobre o mesmo \"feijão\" ou em \"feijões\" diferentes.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Dar um passo largo por cima do objeto, sem saltar.",
        "NÍVEL 2 (AVANÇADO)":  "Saltar com os dois pés juntos de um lado para o outro.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Siga o Mestre Veloz",
        "MISSÃO":  "Imitar todos os movimentos do mestre o mais rápido que puder!",
        "MATERIAL NECESSÁRIO":  "Nenhum",
        "CRIANÇA FAZ":  "Imita os movimentos da mãe.",
        "MÃE FAZ":  "Faz uma sequência cardio: Corrida no lugar, Polichinelo sem salto, etc.",
        "INTERAÇÃO":  "A mãe é o \"mestre\" e a criança o \"aprendiz\". Na rodada seguinte, trocam.",
        "TEMPO":  "2-3 min",
        "NÍVEL 1 (INICIANTE)":  "Fazer a sequência em ritmo de marcha.",
        "NÍVEL 2 (AVANÇADO)":  "Aumentar a velocidade da sequência.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Esqui na Montanha",
        "MISSÃO":  "Esquiar na neve, pulando de um lado para o outro para desviar das árvores!",
        "MATERIAL NECESSÁRIO":  "Nenhum",
        "CRIANÇA FAZ":  "Imita o movimento de esquiar, saltando de um pé para o outro.",
        "MÃE FAZ":  "Salto de patinador (Skater jump).",
        "INTERAÇÃO":  "Ambos \"esquiam\" juntos, como se estivessem na mesma montanha.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Dar um passo largo para o lado em vez de saltar.",
        "NÍVEL 2 (AVANÇADO)":  "Saltar com mais amplitude e velocidade.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Corre Mensageiro",
        "MISSÃO":  "Levar as cartas secretas para o outro lado do reino antes que o tempo acabe!",
        "MATERIAL NECESSÁRIO":  "Dois objetos marcadores",
        "CRIANÇA FAZ":  "Corre de um ponto ao outro.",
        "MÃE FAZ":  "Corrida vai-e-vem (shuttle run).",
        "INTERAÇÃO":  "Missão em equipe: um leva a carta, bate na mão do outro para o próximo ir.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Trote leve entre os pontos.",
        "NÍVEL 2 (AVANÇADO)":  "Corrida em velocidade (sprint).",
        "ESPAÇO":  "❌ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Estátua de Gelo",
        "MISSÃO":  "Ficar duro como gelo e depois derreter completamente quando o sol aparece!",
        "MATERIAL NECESSÁRIO":  "Tapete",
        "CRIANÇA FAZ":  "Inspira puxando os ombros para cima e expira relaxando o corpo para frente.",
        "MÃE FAZ":  "Guia o movimento, fazendo junto.",
        "INTERAÇÃO":  "A mãe narra a transformação de gelo para água.",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Foco na percepção do movimento, sem forçar.",
        "NÍVEL 2 (AVANÇADO)":  "Tenta sentir cada parte do corpo \"derretendo\".",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Alongamento dos Animais",
        "MISSÃO":  "Espreguiçar como os animais da floresta: gato, cachorro e tatu!",
        "MATERIAL NECESSÁRIO":  "Tapete",
        "CRIANÇA FAZ":  "Imita os animais junto com a mãe.",
        "MÃE FAZ":  "Guia a sequência: Gato/Vaca, Cachorro Olhando para Baixo, Tatu-Bolinha.",
        "INTERAÇÃO":  "Fazem os sons dos animais juntos a cada postura.",
        "TEMPO":  "2-3 min",
        "NÍVEL 1 (INICIANTE)":  "Fazer os movimentos com menor amplitude.",
        "NÍVEL 2 (AVANÇADO)":  "Segurar cada postura por 15 segundos.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Borboleta Calma",
        "MISSÃO":  "Ser uma borboleta que bate as asas bem devagar, descansando em uma flor.",
        "MATERIAL NECESSÁRIO":  "Tapete",
        "CRIANÇA FAZ":  "Senta, junta a sola dos pés e balança os joelhos.",
        "MÃE FAZ":  "O mesmo movimento de \"borboleta\", sentindo alongar a virilha.",
        "INTERAÇÃO":  "Cantam uma música suave enquanto \"batem as asas\".",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Manter a postura sem balançar os joelhos.",
        "NÍVEL 2 (AVANÇADO)":  "Balançar os joelhos suavemente.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Cobra e a Concha",
        "MISSÃO":  "Ser uma cobra que se estica para pegar sol e depois se esconde em sua concha.",
        "MATERIAL NECESSÁRIO":  "Tapete",
        "CRIANÇA FAZ":  "Imita os movimentos da mãe no seu próprio ritmo.",
        "MÃE FAZ":  "Sequência: Posição da Cobra e depois Posição da Criança.",
        "INTERAÇÃO":  "A mãe narra: \"Vamos virar uma cobra... agora, vamos nos esconder!\".",
        "TEMPO":  "2 min",
        "NÍVEL 1 (INICIANTE)":  "Na \"Cobra\", manter os cotovelos flexionados.",
        "NÍVEL 2 (AVANÇADO)":  "Estender completamente os cotovelos na \"Cobra\".",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Cheirar a Flor, Soprar a Vela",
        "MISSÃO":  "Cheirar a flor mais cheirosa e soprar a velinha do bolo bem devagar.",
        "MATERIAL NECESSÁRIO":  "Nenhum",
        "CRIANÇA FAZ":  "Inspira pelo nariz (\"cheira a flor\") e expira pela boca (\"sopra a vela\").",
        "MÃE FAZ":  "O mesmo movimento, guiando a criança.",
        "INTERAÇÃO":  "Sentados um de frente para o outro, de mãos dadas.",
        "TEMPO":  "1-2 min",
        "NÍVEL 1 (INICIANTE)":  "Fazer 3 a 4 respirações lentas.",
        "NÍVEL 2 (AVANÇADO)":  "Tentar fazer a expiração durar o dobro da inspiração.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    },
    {
        "NOME":  "Abraço Final",
        "MISSÃO":  "Guardar toda a energia boa da nossa brincadeira no abraço mais forte de todos!",
        "MATERIAL NECESSÁRIO":  "Nenhum",
        "CRIANÇA FAZ":  "Dá um abraço apertado na mãe.",
        "MÃE FAZ":  "Abraça a criança com presença e carinho.",
        "INTERAÇÃO":  "Permanecem abraçados com três respirações profundas.",
        "TEMPO":  "1 min",
        "NÍVEL 1 (INICIANTE)":  "Foco na conexão e no encerramento positivo.",
        "NÍVEL 2 (AVANÇADO)":  "Foco na conexão e no encerramento positivo.",
        "ESPAÇO":  "✔️ Pequeno / ✔️ Grande"
    }
];
